### PR TITLE
Update to Nickel v1.2.0

### PR DESCRIPTION
**Pull request by yannham**

### CODE REVIEW

**Comment by yannham** [comment]
@vkleen the type doesn't show in the manual anymore. Any idea why? Could that be related to the changes to `nickel doc`?

**Comment by vkleen** [comment]
Probably, let me take a look

**Comment by yannham** [comment]
I pushed a tentative fix

**Review by vkleen — APPROVED** [review]
Looks like that worked 🎉

**Comment by yannham** [comment]
Yup, sorry for the preemptive summoning!

**Pull request merged**
