### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by garbas**
- use Nix (`nix develop`) to provide dependencies for the website
- use dependabot to update github actions and npm dependencies
- new workflow (update-flake-lock) to update flake.lock file
- remove ./nickel as git submodule and use flake inputs

### CODE REVIEW

**Review by yannham — APPROVED** [review]
Looks great! I wouldn't have thought of using `nix develop` in the action directly. There's just this annoying deployment error that I'm seeing also on every new Nickel PR. I'm running the CI locally right now to see if I can reproduce. Should be easier to reproduce now in this setting.

**Comment by yannham** [comment]
I can't reproduce locally, and it's frustrating...

**Comment by garbas** [comment]
@yannham I updated the gatbyjs stuff since that fixed the build error. But then I noticed you already did this in master. Would it be ok to use my update?

**Review by yannham — APPROVED** [review]
Look great.

**Pull request merged**
